#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, s: "List[str]", t: "List[str]"):
    ans = True
    st = s + t
    for i in range(N):
        if s[i] != t[i]:
            if st.count(s[i]) > 1 and st.count(t[i]) > 1:
                ans = False
        else:
            if st.count(s[i]) > 2:
                ans = False
    if ans:
        print(YES)
    else:
        print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = [str()] * (N)  # type: "List[str]"
    t = [str()] * (N)  # type: "List[str]"
    for i in range(N):
        s[i] = next(tokens)
        t[i] = next(tokens)
    solve(N, s, t)


if __name__ == '__main__':
    main()
