#!/usr/bin/env python3
import sys


def solve(S: int, T: int):
    ans = 0
    for i in range(max(S, T)+1):
        for j in range(max(S-i, T//(i+1))+1):
            for k in range(max(S-(i+j), T//(i+1)//(j+1))+1):
                if i + j + k <= S and i * j * k <= T:
                    ans += 1
    print(ans)
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    solve(S, T)

if __name__ == '__main__':
    main()
