#!/usr/bin/env python3
import sys


def solve(S: str):
    for i in range(len(S)):
        if S[i] == "6":
            S = S[:i] + "9" + S[i+1:]
        elif S[i] == "9":
            S = S[:i] + "6" + S[i+1:]
    print(S[::-1])
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
