#!/usr/bin/env python3
import heapq
from collections import deque
# Generated by 2.8.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    q = int(input())
    a = list()
    heapq.heapify(a)
    temp = deque()
    for _ in range(q):
        s = list(map(int, input().split()))
        if s[0] == 1:
            temp.append(s[1])
        if s[0] == 2:
            if a:
                print(heapq.heappop(a))
            else:
                print(temp.popleft())
        if s[0] == 3:
            for i in temp:
                heapq.heappush(a, i)
            temp = deque()
    return

if __name__ == '__main__':
    main()
