#!/usr/bin/env python3
import sys


def solve(N: int):
    ans = ""
    while N != 0:
        if N%2 == 0:
            ans += "B"
            N //= 2
        else:
            ans += "A"
            N -= 1
    print(ans[::-1])
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
