#!/usr/bin/env python3
import sys
from scipy.special import comb

def solve(A: int, B: int, K: int):
    ans = ""
    for _ in range(A+B):
        if K <= comb(A+B-1, A-1, exact=True):
            ans += "a"
            A -= 1
        else:
            ans += "b"
            K -= comb(A+B-1, A-1, exact=True)
            B -= 1
    print(ans)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(A, B, K)

if __name__ == '__main__':
    main()
