#!/usr/bin/env python3
# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
import bisect


def main():
    n = int(input())
    a = list(map(int, input().split()))
    q = int(input())
    li = [list() for _ in range(n)]
    for i in range(n):
        li[a[i]-1].append(i)
    for _ in range(q):
        l, r, x = map(int, input().split())
        right = bisect.bisect(li[x-1], r-1)
        left = bisect.bisect_left(li[x-1], l-1)
        print(right-left)


if __name__ == '__main__':
    main()
