#!/usr/bin/env python3
import heapq
# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    li = list()
    s = 0
    Q = int(input())
    for _ in range(Q):
        q = list(map(int, input().split()))
        if q[0] == 1:
            heapq.heappush(li, q[1]-s)
        elif q[0] == 2:
            s += q[1]
        else:
            print(heapq.heappop(li)+s)

if __name__ == '__main__':
    main()
