#!/usr/bin/env python3
import sys


def find_piece(s):
    coordinates = list()
    for i in range(len(s)):
        for j in range(len(s[i])):
            if s[i][j] == "o":
                coordinates.append([i, j])
    return coordinates


def solve(H: int, W: int, S: "List[str]"):
    coordinates = find_piece(S)
    ans = abs(coordinates[0][0] - coordinates[1][0]) + \
        abs(coordinates[0][1] - coordinates[1][1])
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, S)


if __name__ == '__main__':
    main()
