#!/usr/bin/env python3
import sys

def seek(s):
    count0 = 0
    for i in s:
        if i=="0":
            count0 += 1
        else:
            count0 -= 1
        if count0 < 0:
            return False
    if count0 == 0:
        return True
    else:
        return False

def solve(N: int):
    for i in range(1, 2**N):
        s = format(i, f'0{N}b')
        if seek(s):
            for i in s:
                if i == "0":
                    print("(", sep="", end="")
                else:
                    print(")", sep="", end="")
    
            print("\n", end="")
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
