#!/usr/bin/env python3
import sys


def solve(N: int, Q: int, A: "List[int]", L: "List[int]", R: "List[int]", V: "List[int]"):
    ans = 0
    B = list()
    for i in range(N-1):
        ans += abs(A[i]-A[i+1])
        B.append(A[i+1]-A[i])
    for i in range(Q):
        if L[i] < 2 and R[i] > N-1:
            pass
        elif L[i] < 2:
            temp = abs(B[R[i]-1])
            B[R[i]-1] -= V[i]
            ans += abs(B[R[i]-1]) - temp
        elif R[i] > N-1:
            temp = abs(B[L[i]-2])
            B[L[i]-2] += V[i]
            ans += abs(B[L[i]-2]) - temp
        else:
            temp = abs(B[L[i]-2]) + abs(B[R[i]-1])
            B[L[i]-2] += V[i]
            B[R[i]-1] -= V[i]
            ans += abs(B[L[i]-2]) + abs(B[R[i]-1]) - temp 
        print(ans)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    L = [int()] * (Q)  # type: "List[int]"
    R = [int()] * (Q)  # type: "List[int]"
    V = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, Q, A, L, R, V)

if __name__ == '__main__':
    main()
