#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, K: int):
    if N == 1:
        print(K)
        return
    elif N == 2:
        ans = (K * (K-1)) % MOD
        print(ans)
        return
    elif K <= 2:
        print(0)
        return
    ans = K * (K-1) * pow(K-2, N-2, MOD) % MOD
    print(ans)
    return


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    solve(N, K)


if __name__ == '__main__':
    main()
