#!/usr/bin/env python3
import sys


def cal(a, b):
    return a**3 + a**2*b + a*b**2 + b**3


def solve(N: int):
    ans = float("inf")
    j = 10**6
    for i in range(10**6):
        while cal(i, j) >= N and j >= 0:
            ans = min(ans, cal(i, j))
            j -= 1
    print(ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
