#!/usr/bin/env python3
import sys


def solve(N: int, K: int, A: "List[int]", B: "List[int]"):
    ab = {}
    for i in range(N):
        if A[i] in ab:
            ab[A[i]] += B[i]
        else:
            ab[A[i]] = B[i]
    ab = sorted(ab.items(), key=lambda x:x[0])
    for k in ab:
        if K >= int(k[0]):
            K += int(k[1])
    print(K)
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(N, K, A, B)

if __name__ == '__main__':
    main()
