#!/usr/bin/env python3


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n = int(input())
    x = list()
    y = list()
    for i in range(n):
        x1, y1 = map(int, input().split())
        x.append(x1)
        y.append(y1)
    xo = x
    yo = y
    x.sort()
    y.sort()
    ans = [x[-1]-x[0], x[-2]-x[0], x[-1]-x[1], y[-1]-y[0], y[-2]-y[0], y[-1]-y[1]]
    ans.sort()
    if xo.index(x[-1]) == yo.index(y[-1]) and x[-1] == y[-1]:
        print(ans[-3])
    else:
        print(ans[-2])
        

if __name__ == '__main__':
    main()
