#!/usr/bin/env python3


# Generated by 2.5.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    n = int(input())
    li = list()
    ans = 0
    
    for i in range(n):
        t, l, r = map(int, input().split())
        if t == 1:
            li.append([l, r])
        elif t == 2:
            li.append([l, r-0.5])
        elif t == 3:
            li.append([l+0.5, r])
        else:
            li.append([l+0.5, r-0.5])
            
    for i in range(n-1):
        for j in range(i+1, n):
            if li[i][0] <= li[j][0] <= li[i][1] or li[i][0] <= li[j][1] <= li[i][1] or li[j][0] <= li[i][0] <= li[j][1] or li[j][0] <= li[i][1] <= li[j][1]:
                ans += 1
    print(ans)
            
if __name__ == '__main__':
    main()
