#!/usr/bin/env python3
import sys


def solve(N: int, C: "List[int]", P: "List[int]", Q: int, L: "List[int]", R: "List[int]"):
    c_1 = list()
    c_2 = list()
    for i in range(N):
        if C[i] == 1:
            c_1.append(P[i])
            c_2.append(0)
        else:
            c_2.append(P[i])
            c_1.append(0)


    c_1_r = [0] * (N+1)
    c_2_r = [0] * (N+1)
    for i in range(1, N+1):
        c_1_r[i] = c_1_r[i-1] + c_1[i-1]
        c_2_r[i] = c_2_r[i-1] + c_2[i-1]
        
    for i in range(Q):
        print(c_1_r[R[i]] - c_1_r[L[i]-1], c_2_r[R[i]] - c_2_r[L[i]-1])
        
    return


# Generated by 2.3.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    C = [int()] * (N)  # type: "List[int]"
    P = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        C[i] = int(next(tokens))
        P[i] = int(next(tokens))
    Q = int(next(tokens))  # type: int
    L = [int()] * (Q)  # type: "List[int]"
    R = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    solve(N, C, P, Q, L, R)

if __name__ == '__main__':
    main()
