#!/usr/bin/env python3
import sys

MOD = 1000000007  # type: int


def solve(N: int, S: str):
    
    dp = [0]*7
    for s in S[::-1]:
        if s in "atcoder":
            i = "atcoder".index(s)
            if i == len("atcoder") -1:
                dp[i] += 1
            else:
                dp[i] = (dp[i] + dp[i + 1]) % MOD
    
    print(dp[0])
            
    return


# Generated by 2.4.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
