#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n = int(input())
    st = list()
    for i in range(n):
        s, t = input().split()
        st.append([s, t])
    f = 0
    for i in range(n):
        for j in range(0, i):
            if st[i] == st[j]:
                f = 1
        for j in range(i+1, n):
            if st[i] == st[j]:
                f = 1
    if f == 1:
        print(YES)
    else:
        print(NO)
if __name__ == '__main__':
    main()
