#!/usr/bin/env python3


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    xy = input()
    x = xy.split(".")[0]
    y = xy.split(".")[1]
    y = int(y)
    if 0 <= y <= 2:
        print(x+"-")
    elif 3 <= y <= 6:
        print(x)
    else:
        print(x+"+")

if __name__ == '__main__':
    main()
