#!/usr/bin/env python3
import sys
import bisect

def solve(H: int, W: int, N: int, A: "List[int]", B: "List[int]"):
    ans = list()
    for i in range(N):
        ans.append([A[i], B[i]])
    
    A = list(set(A))
    B = list(set(B))
    A.sort()
    B.sort()
    for i in range(N):
        a = bisect.bisect(A, ans[i][0])
        b = bisect.bisect(B, ans[i][1])
        print(a, b)
        
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    A = [int()] * (N)  # type: "List[int]"
    B = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    solve(H, W, N, A, B)

if __name__ == '__main__':
    main()
