#!/usr/bin/env python3
import sys

sys.setrecursionlimit(2000)


def create_s(s, i):
    if i == 0:
        return s
    else:
        return create_s(s, i-1) + [i] + create_s(s, i-1)


def solve(N: int):
    ans = create_s([], N)
    print(*ans)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)


if __name__ == '__main__':
    main()
